blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/John-Jepsen/dsa-quiz-master/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/John-Jepsen/dsa-quiz-master/blob/main/docs/README.md
    about: Check the documentation for answers to common questions